Фронт изменение темы.
jm-review-bot/review-bot pull request #103
Opened 2020-07-17 14:31 UTC by JeRiF74

2020-07-18 15:09 UTC, nanoficator requested changes
Два важных момента:
1. Зацикливается вопрос об удалении темы, при чем количество циклов зависит от того, сколько раз нажималось "Удалить".
2. Не удаляются темы, в которых есть вопросы. По всей видимости, проблема на стороне бэкенда, но устранять придется тебе

Все остальные комментарии по коду ниже

2020-07-18 15:09 UTC, nanoficator commented on pom.xml
> +
Зависимость **popper** можно смело удалять вместе с зависимостью **jquery**, поскольку **popper** и **jquery** уже включены в зависимость **bootstrap**

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +        <!-- Модалка для тем -->
Переименуй в что-то более явное. Например, "Модалка для редактирования темы". Кто знает, какие еще модалки у нас появятся для тем

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                        <h5 class="modal-title theme-title"></h5>
class="theme-title" тоже стоит заменить на что-то более конкретное. Например, на class="edit-theme-title"

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                                <button class="dropdown-item delete-theme-button" type="button">Удалить</button>
Нужно ли тут id="dropdownMenu2"? Соответственно, aria-labelledby="dropdownMenu2" тоже

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                        <button type="button" class="btn btn-primary" id="saveChanging">Сохранить</button>
id="saveChanging" - тоже более подробную информацию бы получить, чтобы потом не путать в JS

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +<script type="text/javascript" src="/webjars/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
Я тут выяснил, что тут ошибка тянется еще с моего первого кода по фронту :)
Вместо
`<script type="text/javascript" src="/webjars/popper.js/1.16.0/popper.min.js"></script>`
я должен был написать
`<script type="text/javascript" src="/webjars/popper.js/1.16.0/umd/popper.min.js"></script>`
т.е. пропустил директорию **umd** в пути. Тогда и проблем с popper'ом у тебя не было бы, за это прошу извинить :)

С учетом твоей правки
`<script type="text/javascript" src="/webjars/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>`
можно вообще удалить скрипт **popper**'а. Но моей внутренний перфекционист требует, чтобы он был явно задан, поэтому предлагаю оставить эти три строчки импорта в следующем виде:
```
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script type="text/javascript" src="/webjars/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="/webjars/popper.js/1.16.0/umd/popper.min.js"></script>
<script type="text/javascript" src="/webjars/bootstrap/4.5.0/js/bootstrap.min.js"></script>
```
У себя потестил конкретно это изменение - все будет ок.

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/static/js/changeThemeService.js
> +        debugger;
Убери все дебагеры, пожалуйста. Для отладки можешь себе оставлять, но в dev'е это будет лишним

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/static/js/changeThemeService.js
> +        async: false ,
async тут не нужен

2020-07-18 15:09 UTC, nanoficator commented on src/main/resources/static/js/changeThemeService.js
> +function closeWindowAndRefreshPage() {
closeWindowAndRefreshPage - мы вроде не страницу обновляем, а список тем. Лучше будет closeWindowAndRefreshThemesList

2020-07-21 07:20 UTC, nanoficator requested changes
1. Верни на место css/reviewBot.css
2. Верни на место js/addTheme.js 
3. После удаления темы не обновляется список тем, только после обновления страницы (возможно причина кроется в пунктах 1 и 2 - в консоли браузера есть ошибки)
4. Есть один комментарий по коду (см. ниже)

2020-07-21 07:20 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
Убери id="dropdownMenu2" и aria-labelledby="dropdownMenu2"

2020-07-21 09:13 UTC, nanoficator requested changes
1. Не обновляется список тем после удаления (приходится обновлять страницу)
2. После добавления новой темы или удаления одной из существующих не работает ни одна из кнопок "Редактировать тему"

Могу пока лишь предположить, что проблема в обработчиках событий

2020-07-21 09:13 UTC, nanoficator commented on src/main/resources/static/js/addTheme.js
> +)
Что за изменение и почему оно тут отображается?

2020-07-21 16:01 UTC, nanoficator submitted a review, later dismissed

2020-07-23 09:51 UTC, IvanCherepica approved these changes

2020-07-23 09:51 UTC, merged