api_feedback
jm-review-bot/review-bot pull request #110
Opened 2020-07-23 08:35 UTC by KolyanRUS

GET-запросы, связанные с фидбэками

2020-07-23 10:02 UTC, nanoficator requested changes
При отправки GET на оба url'а падает эксепшен:
`org.hibernate.QueryException: could not resolve property: reviewerName of: spring.app.model.Feedback`
Соответсвенно, возвращается статус 500

2020-07-27 11:50 UTC, IvanCherepica commented on src/main/java/spring/app/controller/AdminFeedbackRestController.java
> +        FeedbackDto feedbackDtoById = feedbackService.getFeedbackDtoById(feedbackId);
Тебе нужен только комент. Зачем для этого собирать всю дто полностью? Напиши отдельный метод, который тебе достает только комент и возвращает строку

2020-07-27 11:51 UTC, IvanCherepica commented on src/main/resources/static/js/feedbackPageService.js
> +function getAllFeedbacksDto() {
Зачем это здесь? По задаче нужно было написать только api. Удали лишнее

2020-07-30 10:23 UTC, IvanCherepica commented on src/main/java/spring/app/dao/impl/FeedbackDaoImpl.java
> +        return entityManager.createQuery("SELECT new java.lang.String(f.comment) FROM Feedback f WHERE f.id = :idFeedback", String.class)
Зачем тут так сделано? Разве ты не можешь просто сразу достать стрингу?

2020-07-30 16:06 UTC, IvanCherepica approved these changes

2020-07-30 16:06 UTC, merged