front_feedback
jm-review-bot/review-bot pull request #119
Opened 2020-07-29 10:43 UTC by KolyanRUS

2020-07-29 20:01 UTC, nanoficator requested changes

2020-07-29 20:01 UTC, nanoficator commented on src/main/java/spring/app/configuration/initializator/TestDataInit.java
> +        feedbackService.addFeedback(feedback5);
Предлагаю сразу напихать разных существующих уже студентов и ревью. Может пригодиться в будущих тестах (например, при удалении сущностей), может раньше позволить выявить баги

2020-07-29 20:01 UTC, nanoficator commented on src/main/resources/static/js/feedbackPageService.js
> +                "#"+dec2hex(255)+dec2hex(0)+dec2hex(Math.round((63.75)*(10-ratingReviewer)));
У тебя получилось 1 - зеленый, 10 - красный. Должно быть наоборот

2020-07-29 20:01 UTC, nanoficator commented on src/main/java/spring/app/dto/FeedbackDto.java
> +        this.studentComment = studentComment;
В моем понимании, поля **studentComment** здесь не должно быть, поскольку на фронте прикручивается отдельная кнопка, чтобы текст комментария выгружать из БД

2020-07-29 20:01 UTC, nanoficator commented on src/main/resources/templates/feedback.html
> +                <th>button_for_viewing_the_comment</th>
Название последней колонки необходимо переименовать

2020-07-29 20:01 UTC, nanoficator commented on src/main/resources/templates/feedback.html
> +<script type="text/javascript" src="/js/feedbackPageService.js"></script>
Все ли скрипты нужны на этой странице?

2020-07-29 20:01 UTC, nanoficator commented on src/main/resources/static/js/feedbackPageService.js
> +                  </td>
Карточка, п.3:

> В последнем столбце таблицы должна быть кнопка "комментарий" по нажатии на который отправляется ajax запрос на получение текста комментария, относящегося к данной записи. У данной кнопки должен быть аттрибут data-feedback-id, которая содержит id текущего отзыва

Насколько понимаю, ты уже в каждую кнопку при загрузке странице закладываешь текст комментария, а он должен извлекаться из БД только нажатию на кнопку

2020-07-31 10:46 UTC, IvanCherepica submitted a review, later dismissed

2020-08-07 18:44 UTC, IvanCherepica approved these changes

2020-08-07 18:45 UTC, merged