Api reviewer rest controller
jm-review-bot/review-bot pull request #123
Opened 2020-07-29 20:38 UTC by JeRiF74

2020-07-30 12:51 UTC, nanoficator requested changes
1. GET: /admin/theme/{themeId}/reviewer/notInThisTheme - не работает: выдаются все ревьюверы почему-то
2. Общепринято, что все ключевые слова (SELECT, DELETE и пр.) в SQL-запросах пишутся CapsLock, надо бы тоже поправить
3. Вопрос с "лишними" у сущности ReviewerDto - Ульви обещал поднять на скраме

2020-08-01 16:33 UTC, nanoficator requested changes
GET-запрос `/admin/theme/{themeId}/reviewer/notInThisTheme` может вернуть также и ревьюеров, которые состоят в это теме, если она у них не единственная

2020-08-04 14:41 UTC, IvanCherepica commented on src/main/java/spring/app/dao/abstraction/UserDao.java
> +    void deleteReviewerFromTheme (long themeId , long reviewerId);
Эта операция так же должна требовать транзакцию, как и вс методы изменения/добавления/удаления

2020-08-04 14:41 UTC, IvanCherepica approved these changes

2020-08-04 14:43 UTC, merged