commit 1.1
jm-review-bot/review-bot pull request #130
Opened 2020-08-03 13:37 UTC by JeRiF74

Поменял стиль вопросов .

2020-08-03 13:59 UTC, nanoficator requested changes
1. Выводится ID темы, а должен порядковый номер
2. Сделай так, чтобы текст вопроса не переносился на следующую строку после номера, а шел сразу после него в той же строке через пробел. Также, судя по всему, номер вопроса/темы имеет меньший размер шрифта, чем текст вопроса

2020-08-03 17:43 UTC, nanoficator requested changes

2020-08-03 17:43 UTC, nanoficator commented on src/main/resources/static/js/questionPageService.js
> +}
Этот метод уже существует в **_editThemeService.js_**. Дублировать его не нужно

2020-08-04 14:46 UTC, IvanCherepica approved these changes

2020-08-04 14:46 UTC, merged