Юзер: Принять ревью п.1 и п.2 - реализовал (НА БАЗЕ ДЭВА) то, что отмечено зелёным.
jm-review-bot/review-bot pull request #157
Opened 2020-08-17 00:42 UTC by KolyanRUS

2020-08-17 19:02 UTC, nanoficator requested changes
Не совсем понятно: зачем пользователю скрывать темы со свободной защитой, но при этом бот

2020-08-17 19:02 UTC, nanoficator commented on src/main/java/spring/app/core/steps/UserTakeReviewAddTheme.java
> +        List<Theme> themes = themeService.getAllThemes().stream().filter(s->s.getThemeType().equals("fixed")).collect(Collectors.toList());
Не проще ли сразу из БД выгружать темы с определенным типом?

2020-08-17 19:02 UTC, nanoficator commented on src/main/java/spring/app/core/steps/UserTakeReviewAddTheme.java
>              } else {
Если из БД не выгружать темы со свободной защитой, то и проверять на тип не будет необходимости

2020-08-20 16:55 UTC, IvanCherepica commented on src/main/java/spring/app/core/steps/UserTakeReviewAddTheme.java
> +        String themePositionsRegister = storageService.getUserStorage(context.getVkId(), USER_TAKE_REVIEW_ADD_THEME).get(1);
А зачем нам тут вообще это? В предыдущей версии кода мы просто брали темы и стримом делали из них лист позиций

2020-08-20 16:56 UTC, IvanCherepica commented on src/main/java/spring/app/core/steps/UserTakeReviewAddTheme.java
> +        List<String> themePositionsList = Arrays.asList(themePositionsRegister.split("_"));
Почему теперь мы сохраняем позиции в предыдущем шаге? В методе enter

2020-08-20 16:59 UTC, IvanCherepica commented on src/main/java/spring/app/core/steps/UserTakeReviewAddTheme.java
> +        List<String> themePositionsList = Arrays.asList(themePositionsRegister.split("_"));
А нельзя в предыдущем методе сразу сохранить лист, или массив, что бы тут не приходилось сплитить?

2020-08-21 09:35 UTC, IvanCherepica approved these changes

2020-08-21 09:35 UTC, merged