Review data
jm-review-bot/review-bot pull request #160
Opened 2020-08-17 15:59 UTC by mklopotnuk

2020-08-18 15:50 UTC, nanoficator requested changes
Конфликт с веткой необходимо устранить + комментарий по коду

2020-08-18 15:50 UTC, nanoficator commented on src/main/java/spring/app/core/steps/ExaminerAddNewStudentReview.java
>                      student.getFirstName(),
Тут уже используется String.format(), который спасает от конкатенаций, которые ты добавил

2020-08-18 18:16 UTC, mklopotnuk commented on src/main/java/spring/app/core/steps/ExaminerAddNewStudentReview.java
>                      student.getFirstName(),
Готово, поправил, и конфликт разрешил.

2020-08-19 14:28 UTC, IvanCherepica approved these changes

2020-08-19 14:28 UTC, merged