User feedback
jm-review-bot/review-bot pull request #54
Opened 2020-05-26 22:07 UTC by Shpoongled717

Пункт "Обратная связь" из тз

2020-05-31 12:47 UTC, IvanCherepica commented on src/main/java/spring/app/core/steps/UserFeedbackReviewAssessment.java
> +    int lowBound;
Почему не private?

2020-05-31 12:47 UTC, IvanCherepica commented on src/main/java/spring/app/core/steps/UserFeedbackReviewAssessment.java
> +    int upBound;
и тут

2020-05-31 12:48 UTC, IvanCherepica commented on src/main/java/spring/app/core/steps/UserFeedbackReviewerAssessment.java
> +    int lowBound;
Везде, где аннотация Value поставить приватный модификатор

2020-06-18 12:05 UTC, dshepelev15 commented on src/main/java/spring/app/core/steps/UserFeedbackReviewerAssessment.java
> +public class UserFeedbackReviewerAssessment extends Step {
Может стоит подумать об объединении классов UserFeedbackReviewAssessment и UserFeedbackReviewerAssessment?

Они отличаются только методом getDynamicText и действиями, которые необходимо сделать после успешно введенного числа из диапазона low/up bounds. Мб сделать какой-то метод типа `successHandler` , в котором будет описана логика успешной обработки введенного числа пользователем.

Что думаешь?

2020-06-18 12:05 UTC, dshepelev15 commented on src/main/resources/application.properties
> +review.early_start=5
А где мы используем эти проперти? Или это последствия мерджа с какой-то другой веткой?

2020-06-18 19:03 UTC, Swofford18 commented on src/main/resources/application.properties
> +review.early_start=5
Да, эти проперти сейчас не используются. Но функционал на убран, а закомменчен.

2020-06-21 17:33 UTC, dshepelev15 requested changes

2020-06-21 17:33 UTC, dshepelev15 commented on src/main/java/spring/app/core/steps/UserBaseFeedbackStep.java
> +        return lowBound + " до " + upBound + "?";
Как то здесь не очень выглядит отсутствие предлога `от`. Почему он размещен в дочерних классах?

2020-06-22 10:48 UTC, IvanCherepica approved these changes

2020-06-22 10:49 UTC, merged