Add api change theme position
jm-review-bot/review-bot pull request #81
Opened 2020-07-03 13:39 UTC by nanoficator

2020-07-03 14:02 UTC, dshepelev15 requested changes

2020-07-03 14:02 UTC, dshepelev15 commented on src/main/java/spring/app/core/api/controllers/ChangeThemePosition.java
> +            Theme themeToUp = themeService.getThemeById(Long.parseLong(themeId));       // Тема, которую необходимо переместить
Лучше стоит вынести логику перемещения тем на уровень сервиса

2020-07-03 14:02 UTC, dshepelev15 commented on src/main/java/spring/app/core/api/controllers/ChangeThemePosition.java
> +            Theme themeToUp = themeService.getThemeById(Long.parseLong(themeId));       // Тема, которую необходимо переместить
Зачем для каждой строки установлен комментарий?

2020-07-03 14:02 UTC, dshepelev15 commented on src/main/java/spring/app/core/api/controllers/ChangeThemePosition.java
> +            themeService.updateTheme(themeToDown);                                      // Вносим изменения в тему через ThemeService
Логика up и down очень похожа. Лучше стоит их объединить в единый метод, отправляя +1 или -1 для перемещения позиции темы

2020-07-04 08:48 UTC, dshepelev15 requested changes

2020-07-04 08:48 UTC, dshepelev15 commented on src/main/java/spring/app/service/impl/ThemeServiceImpl.java
> +                    themeDao.update(theme);
Перемещение других связанных объектов можно сделать через один hql запрос в DAO

2020-07-04 10:56 UTC, dshepelev15 commented on src/main/java/spring/app/core/controller/ChangeThemePosition.java
> +public class ChangeThemePosition {
Почему название класса без суффикса `Controller` ? Лучше явно описывать название класса и его роль в названии

2020-07-04 10:56 UTC, dshepelev15 commented on src/main/java/spring/app/core/controller/ChangeThemePosition.java
> +        this.themeService = themeService;
Если мы используем конструктор и хотим подцепить themeService, то начиная с версии Spring 4.3 аннотация @Autowired над конструктором не нужна. 

Но вообще, почему не сделать просто @Autowired над полем без дополнительных строк кода с конструктором?

2020-07-04 10:56 UTC, dshepelev15 commented on src/main/java/spring/app/core/controller/ChangeThemePosition.java
> +            return new ResponseEntity<>("Тема перемещена на одну позицию вверх", HttpStatus.OK);
Как мне советовал ментор, лучше использовать статичные методы ResponseEntity

Например, ```ResponseEntity.ok("Твоё сообщение")``` или ```ResponseEntity.status(HttpStatus.BAD_REQUEST). ... build()```

2020-07-04 10:56 UTC, dshepelev15 commented on src/main/java/spring/app/core/controller/ChangeThemePosition.java
> +            return new ResponseEntity<>(exception.getMessage(), HttpStatus.BAD_REQUEST);
Аналогично выше (про ResponseEntity)

2020-07-04 10:56 UTC, dshepelev15 commented on src/main/java/spring/app/service/impl/ThemeServiceImpl.java
> +                    themeDao.update(theme);
Так как щас у тебя в задачи shift=1 запросов будет мало. Но если shift будет большим, то для каждого необходимого объекта ты будешь делать отдельный запрос - это не очень, с точки зрения производительности.

2020-07-04 10:56 UTC, dshepelev15 commented on src/main/java/spring/app/service/impl/ThemeServiceImpl.java
> +                    .append(currentPosition);
Мне кажется, что `String.format` - лучше использовать для читабельности в данном случае

2020-07-04 10:56 UTC, dshepelev15 commented on src/main/java/spring/app/dao/impl/ThemeDaoImpl.java
> +    }
Найс (хех) :)

2020-07-06 19:26 UTC, IvanCherepica commented on src/main/java/spring/app/core/controller/ThemePositionController.java
> +public class ThemePositionController {
Склонить изменения из ветки theme_crud и перенести всё содержимое этого класса в ThemeController (Возможно, уже будет перименовано в AdminThemeRestController)

2020-07-07 11:29 UTC, IvanCherepica approved these changes

2020-07-07 11:30 UTC, merged