start_of_the_review__reminder_to_the_reviewer
jm-review-bot/review-bot pull request #85
Opened 2020-07-05 05:10 UTC by KolyanRUS

Исправил баг из карточки "Начало ревью: напоминание ревьюеру".

2020-07-11 16:41 UTC, nanoficator requested changes
Баг устранен, но есть одно **но**:

2020-07-11 16:41 UTC, nanoficator commented on src/main/java/spring/app/core/BotScheduler.java
> +import jdk.nashorn.internal.codegen.types.BooleanType;
Лишний импорт, который не дает запустить приложение. Убери его

2020-07-13 08:33 UTC, nanoficator approved these changes
Порядок

2020-07-13 15:42 UTC, IvanCherepica approved these changes

2020-07-13 15:42 UTC, merged