Создал api Question , исправил все вопросы которые были заданы мне , …
jm-review-bot/review-bot pull request #87
Opened 2020-07-07 16:07 UTC by JeRiF74

…протестировал , все методы работают.

2020-07-07 18:14 UTC, dshepelev15 requested changes

2020-07-07 18:14 UTC, dshepelev15 commented on src/main/java/spring/app/dao/impl/QuestionDaoImpl.java
> +                .executeUpdate();
А здесь не лучше использовать `entityManager.remove`, как советовал Иван?

2020-07-07 18:14 UTC, dshepelev15 commented on src/main/java/spring/app/dao/impl/QuestionDaoImpl.java
> +        List<QuestionDto> list = entityManager.createQuery("SELECT new spring.app.dto.QuestionDto(q.id,q.question,q.position,q.weight) FROM Question q WHERE q.id = :id", QuestionDto.class)
А почему здесь отсутствует 5-ое поле в конструкторе? А именно `q.answer`?

2020-07-08 11:51 UTC, IvanCherepica approved these changes

2020-07-08 11:51 UTC, merged