front_adding_a_theme
jm-review-bot/review-bot pull request #92
Opened 2020-07-11 00:02 UTC by KolyanRUS

Создана форма отправки POST-запроса с новым названием темы.
Просто отправляется ajax-овский POST-запрос, конкретных действий по добавлению этой темы в БД или отображаемый список на странице не осуществляется (это вроде и не требовалось в карточке).

2020-07-11 08:34 UTC, nanoficator requested changes
Нужно много чего переделывать

2020-07-11 08:34 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                    <div id="myModal" class="modal fade">
id="myModal" надо заменить на что-то более описывающее функционал. Соответственно, href="#myModal" тоже изменится

2020-07-11 08:34 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                                    <h4 class="modal-title">Добавление темы</h4>
В заголовке слева должно быть "Добавление темы", а справа кнопка для закрытия модалки. У тебя наоборот получилось

2020-07-11 08:34 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                                    <button type="button" class="btn btn-primary" onclick="addTheme()">Сохранить</button>
У меня по нажатию "Сохранить" падает исключение:
`11:20:50.491  WARN 8012 - [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'multipart/form-data;boundary=----WebKitFormBoundarynOLiJK0BuvEbof8w;charset=UTF-8' not supported]`
и ничего не происходит.

Кроме этого, рекомендую в класс этой кнопки добавить **add-new-theme** и по названию этого класса уже ловить событие нажатия на эту кнопку в JS

2020-07-11 08:34 UTC, nanoficator commented on src/main/resources/static/js/themePageService.js
> +}
В задании табличке сказано: "По нажатии на кнопку "Сохранить" должен быть отправлен POST запрос на url /api/admin/theme. Запрос отправить спомощью AJAX". Здесь ключевой момент "спомощью AJAX", который у тебя не реализован.

Кроме того, у тебя здесь везде присутствуют стандартные методы JS, хотя предпочтительнее использовать JQuery. Т.е., например, по нажатию кнопки "Сохранить" должен присутствовать соответствующий обработчик события, который будет сериализовывать форму и с помощью AJAX отправлять на back ее. Пример отправки AXAJ является метод **getAllThemesDto()** в файле **themePageService.js**.

2020-07-11 09:26 UTC, nanoficator commented
И еще: думаю, что стоит вынести всю логику добавления новой темы в отдельный JS-файл и назвать его, например, "addThemeService.js"

2020-07-13 09:58 UTC, nanoficator approved these changes
Добавление темы отрабатывает. Пока что вручную добавляются **criticalWeight** и **reviewPoint**: их, если не ошибаюсь, необходимо будет убрать после [изменения архитектуры проекта](https://github.com/jm-review-bot/review-bot/pull/95)

2020-07-13 14:52 UTC, nanoficator requested changes
Нужны дополнительно незначительные изменения ввиду некорректно изначально заданной карточки задания

2020-07-13 14:52 UTC, nanoficator commented on src/main/resources/templates/theme.html
> +                            </div>
Еще необходимы поля для ввода criticalWeight и reviewPoint

2020-07-13 14:52 UTC, nanoficator commented on src/main/resources/static/js/addTheme.js
> +            reviewPoint:4
После добавления полей для ввода criticalWeight и reviewPoint в html-файле необходимо их тут также добавить к полям объекта **json**

2020-07-13 16:42 UTC, IvanCherepica commented on src/main/resources/static/js/addTheme.js
> +        let value = $('#idInputForNameOfTheNewTheme').val();
заменить title

2020-07-13 16:44 UTC, IvanCherepica commented on src/main/resources/static/js/addTheme.js
> +            contentType: "application/json",
contentType и date лучше вынести сразу после поля type

2020-07-15 18:02 UTC, closed without merging