Implement theme entity inheritance
jm-review-bot/review-bot pull request #95
Opened 2020-07-13 09:26 UTC by dshepelev15

2020-07-13 14:45 UTC, nanoficator submitted a review, later dismissed

2020-07-13 16:23 UTC, nanoficator requested changes

2020-07-13 16:23 UTC, nanoficator commented on src/main/java/spring/app/core/steps/UserPassReviewAddTheme.java
>      }
1. Убери инициализацию переменной **themeList**
2. У тебя переменная themeRow не используется, хотя должна быть на месте **themeList.toString()**

2020-07-13 16:32 UTC, nanoficator approved these changes

2020-07-14 12:27 UTC, IvanCherepica approved these changes

2020-07-14 12:27 UTC, merged